[theme]
base="light"


[client]
# This completely hides the top-right "Deploy" button and the main menu burger.
# It saves vertical screen space and helps prevent layout shifting!
showErrorDetails = true
toolbarMode = "minimal"